Tweaked the aws install function

diff --git a/alias b/alias
--- a/alias
+++ b/alias
@@ -131,12 +131,9 @@ install =
       BREW_CLI=$(which brew) || { echo "ERROR: brew not installed.  Please install brew: https://brew.sh/" 1>&2 ; return 1 ; }
       JQ_CLI=$(which jq) || { echo "ERROR: jq not installed, please install with \"brew install jq\"." 1>&2 ;  }
       JP_CLI=$(which jp) || { echo "ERROR: jp not installed, please install with \"brew install jp\"" 1>&2 ;  }
-      GETOPT_CLI=[ -x /usr/local/opt/gnu-getopt/bin/getopt ] ||
-      {
-          echo "ERROR: gnugetopt not installed.  Please install GNU getopt and re-run \"aws install\"."  1>&2
-          echo "If you are on Mac OSX, use brew to install Gnu-getopt and/or see https://formulae.brew.sh/formula/gnu-getopt"  1>&2
-          return 1
-      }
+      if [ ! -x /usr/local/opt/gnu-getopt/bin/getopt ]; then
+        echo "ERROR: gnu-getopt not installed.  Please install with \"brew install gnu-getopt\""  1>&2
+      fi
     }
     [ $($UNAME_CLI) = "Linux" ] && {
       echo "OS: Linux"
@@ -186,7 +183,7 @@ install =
 
     # Install aws-mfa Python script using pip3
     echo "Installing aws-mfa Python script using pip3, please wait..."
-    $PIP3_CLI install --user --upgrade aws-mfa
+    $PIP3_CLI install --user --upgrade aws-mfa  2>1 > /dev/null
 
     AWS_MFA_CLI=$(which aws-mfa) ||
     {
