Add the aliases: - ecr-list-repositories - ecr-scan-findings - sh-quick-report
Clean up some commands that aren't checked before use.

diff --git a/alias b/alias
--- a/alias
+++ b/alias
@@ -17,11 +17,12 @@ eb = elasticbeanstalk
 ec = elasticache
 sc = servicecatalog
 sg = security-group
+sh = securityhub
 
 tostring =
   !f() {
     JQ_CLI=$(which jq) || { echo "ERROR: jq not installed."  1>&2 ; return 1 ; }
-    cat "${1}" | jq 'tostring'
+    cat "${1}" | ${JQ_CLI} 'tostring'
   }; f
 
 # List or set your region
@@ -422,8 +423,8 @@ list-virtual-mfa =
     AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
     JQ_CLI=$(which jq) || { echo "ERROR: jq not installed." 1>&2 ; return 1 ; }
     ${AWS_CLI} whoami > /dev/null || { return 1 ; }
-    [ "${1}" ]    && $AWS_CLI iam list-mfa-devices --user-name ${1} | jq -r '.MFADevices[] | "Enabled: \(.EnableDate), ARN: \(.SerialNumber)"'
-    [ -z "${1}" ] && $AWS_CLI iam list-mfa-devices | jq -r '.MFADevices[] | "Enabled: \(.EnableDate), ARN: \(.SerialNumber)"'
+    [ "${1}" ]    && $AWS_CLI iam list-mfa-devices --user-name ${1} | ${JQ_CLI} -r '.MFADevices[] | "Enabled: \(.EnableDate), ARN: \(.SerialNumber)"'
+    [ -z "${1}" ] && $AWS_CLI iam list-mfa-devices | ${JQ_CLI} -r '.MFADevices[] | "Enabled: \(.EnableDate), ARN: \(.SerialNumber)"'
   }; f
 
 
@@ -441,7 +442,7 @@ delete-virtual-mfa =
         return 1
     fi
     ${AWS_CLI} whoami > /dev/null || { return 1 ; }
-    account_id=$($AWS_CLI sts get-caller-identity --output json | jq -r '.Account')
+    account_id=$($AWS_CLI sts get-caller-identity --output json | ${JQ_CLI} -r '.Account')
     $AWS_CLI iam delete-virtual-mfa-device--serial-number "arn:aws:iam::${account_id}:mfa/$1"
   }; f
 
@@ -484,12 +485,13 @@ assume =
   !f() {
     AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
     [ "${1}" ] || { echo "ERROR: Missing an argument" 1>&2 ; echo "Usage: aws assume <role-arn>"1>&2 ; return 1; }
+    JQ_CLI=$(which jq) || { echo "ERROR: jq not installed." 1>&2 ; return 1 ; }
     ${AWS_CLI} whoami > /dev/null || { return 1 ; }
 
     res=$($AWS_CLI sts assume-role --role-arn ${1} --role-session-name session)
     if echo $res | grep -q AccessKeyId; then
         echo $res \
-        | jq -r '
+        | ${JQ_CLI} -r '
         "","[\(.Credentials.AccessKeyId)]",
         "aws_access_key_id     = \(.Credentials.AccessKeyId)",
         "aws_secret_access_key = \(.Credentials.SecretAccessKey)",
@@ -497,7 +499,7 @@ assume =
         "aws_security_token    = \(.Credentials.SessionToken)"
         ' \
         >> ${HOME}/.aws/credentials
-        echo $res | jq -r '"AWS_PROFILE=\(.Credentials.AccessKeyId)"'
+        echo $res | ${JQ_CLI} -r '"AWS_PROFILE=\(.Credentials.AccessKeyId)"'
     fi
   }; f
 
@@ -511,7 +513,7 @@ running-instances =
   !f() {
     AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
     ${AWS_CLI} whoami > /dev/null || { return 1 ; }
-    $AWS_CLI ec2 describe-instances \
+    ${AWS_CLI} ec2 describe-instances \
     --filter Name=instance-state-name,Values=running \
     --output table \
     --query 'Reservations[].Instances[].{ID: InstanceId,Hostname: PublicDnsName,Name: Tags[?Key==`Name`].Value | [0],Type: InstanceType, Platform: Platform || `Linux`}'
@@ -618,7 +620,7 @@ public-ports =
 my-ip =
   !f() {
     CURL_CLI=$(which curl) || { echo "ERROR: curl not installed." 1>&2 ; return 1 ; }
-    $CURL_CLI https://checkip.amazonaws.com
+    ${CURL_CLI} https://checkip.amazonaws.com
   }; f
 
 # allow-my-ip
@@ -825,11 +827,12 @@ find-ssh-open =
 get-asg-instance-ips =
   !f() {
     AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
+    JQ_CLI=$(which jq) || { echo "ERROR: jq not installed." 1>&2 ; return 1 ; }
     [ -z "${1}" ] &&
       { echo "ERROR: Missing an argument" 1>&2 ; echo "Usage: aws get-asg-instance-ips <ASG Name>" 1>&2; return 1;  }
     ${AWS_CLI} whoami > /dev/null || { return 1 ; }
     asg_name=${1}
-    ${AWS_CLI} ec2 describe-instances --filters "Name=tag:aws:autoscaling:groupName,Values=${asg_name}" | jq -r '.Reservations[].Instances[].PrivateIpAddress'
+    ${AWS_CLI} ec2 describe-instances --filters "Name=tag:aws:autoscaling:groupName,Values=${asg_name}" | ${JQ_CLI} -r '.Reservations[].Instances[].PrivateIpAddress'
   }; f
 
 # find-host-by-instance-id
@@ -837,11 +840,12 @@ get-asg-instance-ips =
 find-host-by-instance-id =
   !f() {
     AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
+    JQ_CLI=$(which jq) || { echo "ERROR: jq not installed." 1>&2 ; return 1 ; }
     [ -z "${1}" ] &&
       { echo "ERROR: Missing an argument" 1>&2 ; echo "Usage: aws find-host-by-instance-id <instance ID>" 1>&2; return 1;  }
     ${AWS_CLI} whoami > /dev/null || { return 1 ; }
     instance_id=${1}
-    ${AWS_CLI} ec2 describe-instances --filters "Name=instance-id,Values=${instance_id}" | jq -r '.Reservations[].Instances[].PrivateIpAddress' | sed -E 's/\./-/g; s/^/ip-/'
+    ${AWS_CLI} ec2 describe-instances --filters "Name=instance-id,Values=${instance_id}" | ${JQ_CLI} -r '.Reservations[].Instances[].PrivateIpAddress' | sed -E 's/\./-/g; s/^/ip-/'
   }; f
 
 #find-instance-by-public-ip
@@ -849,10 +853,11 @@ find-host-by-instance-id =
 find-instance-by-public-ip =
   !f() {
     AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
+    JQ_CLI=$(which jq) || { echo "ERROR: jq not installed." 1>&2 ; return 1 ; }
     [ -z "${1}" ] &&
       { echo "ERROR: Missing an argument" 1>&2 ; echo "Usage: aws find-instance-by-public-ip <public ip>" 1>&2; return 1;  }
     ${AWS_CLI} whoami > /dev/null || { return 1 ; }
-    ${AWS_CLI} ec2 describe-instances --filters "Name=ip-address,Values=$1" | jq -r '.Reservations[].Instances[].Tags[] | select(.Key == "Name").Value'
+    ${AWS_CLI} ec2 describe-instances --filters "Name=ip-address,Values=$1" | ${JQ_CLI} -r '.Reservations[].Instances[].Tags[] | select(.Key == "Name").Value'
   }; f
 
 #find-nat-gateway-by-public-ip
@@ -860,10 +865,11 @@ find-instance-by-public-ip =
 find-nat-gateway-by-public-ip =
   !f() {
     AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
+    JQ_CLI=$(which jq) || { echo "ERROR: jq not installed." 1>&2 ; return 1 ; }
     [ -z "${1}" ] &&
       { echo "ERROR: Missing an argument" 1>&2 ; echo "Usage: aws find-nat-gateway-by-public-ip <public ip>" 1>&2; return 1;  }
     ${AWS_CLI} whoami > /dev/null || { return 1 ; }
-    ${AWS_CLI} ec2 describe-nat-gateways | jq -r '.NatGateways[] | select(.NatGatewayAddresses[].PublicIp == "'$1'") | .Tags[] | select(.Key == "Name").Value'
+    ${AWS_CLI} ec2 describe-nat-gateways | ${JQ_CLI} -r '.NatGateways[] | select(.NatGatewayAddresses[].PublicIp == "'$1'") | .Tags[] | select(.Key == "Name").Value'
   }; f
 
 #list-igw
@@ -949,8 +955,9 @@ get-instance-id-from-dns =
 log-groups =
   !f() {
     AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
+    JQ_CLI=$(which jq) || { echo "ERROR: jq not installed." 1>&2 ; return 1 ; }
     ${AWS_CLI} whoami > /dev/null || { return 1 ; }
-    ${AWS_CLI} logs describe-log-groups | jq '.logGroups[].logGroupName'  | sed 's/\"//g'
+    ${AWS_CLI} logs describe-log-groups | ${JQ_CLI} '.logGroups[].logGroupName'  | sed 's/\"//g'
   }; f
 
 #last-log
@@ -975,7 +982,7 @@ last-log =
 ##########
 ## ECR ###
 ##########
-#docker-ecr-login
+# docker-ecr-login
 # Usage: aws docker-ecr-login
 docker-ecr-login =
   !f() {
@@ -988,4 +995,78 @@ docker-ecr-login =
     ${DOCKER_CLI} login -u AWS -p $passwd $endpoint
   }; f
 
+# ecr-list-repositories
+ecr-list-repositories =
+  !f() {
+    AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
+    JQ_CLI=$(which jq) || { echo "ERROR: jq not installed." 1>&2 ; return 1 ; }
+    ${AWS_CLI} whoami > /dev/null || { return 1 ; }
+    ${AWS_CLI} ecr describe-repositories   |  jq -r '.repositories[].repositoryArn'
+  }; f
+
+
+# ecr-scan-findings
+# Usage: aws ecr-scan-findings <repo name>
+ecr-scan-findings =
+  !f() {
+    AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
+    JQ_CLI=$(which jq) || { echo "ERROR: jq not installed." 1>&2 ; return 1 ; }
+    [ -z "${1}" ] &&
+      { echo "ERROR: Missing an argument" 1>&2 ; echo "Usage: aws evoke-my-ip <security group name> <protocol> <port>" 1>&2; return 1;  }
+    ${AWS_CLI} whoami > /dev/null || { return 1 ; }
+    ${AWS_CLI} ecr describe-image-scan-findings --repository-name "${1}" --image-id imageTag=latest | ${JQ_CLI} -r '.imageScanFindings.findings[] | "\(.severity) \(.name) \(.uri)"' | sort
+  }; f
+
+
+
+
+
+##################
+## Securityhub ###
+##################
+# sh-quick-report
+# Usage: sh-quick-report
+sh-quick-report =
+  !f() {
+    AWS_CLI=$(which aws) || { echo "ERROR: I can't seem to find the AWS binary in the path." 1>&2 ; return 1 ; }
+    JQ_CLI=$(which jq) || { echo "ERROR: jq not installed." 1>&2 ; return 1 ; }
+
+    $AWS_CLI whoami > /dev/null || { return 1 ; }
+    CRITICAL=$(mktemp --suffix=.json)
+    HIGH=$(mktemp --suffix=.json)
+    MEDIUM=$(mktemp --suffix=.json)
+    LOW=$(mktemp --suffix=.json)
+    INFO=$(mktemp --suffix=.json)
+
+    trap 'echo "EXIT detected with exit status $?" ; rm -f "$CRITICAL"; rm -f "$HIGH"; rm -f "$MEDIUM"; rm -f "$LOW"; rm -f "$INFO"' EXIT
+    echo "Security Hub Quick Summary Report"
+    echo "================================="
+
+    ${AWS_CLI}  securityhub get-findings --filters '{"SeverityLabel":[{"Value": "CRITICAL","Comparison":"EQUALS"}],"WorkflowStatus": [{"Value":"NEW","Comparison":"EQUALS"}],"RecordState":[{"Value":"ACTIVE","Comparison":"EQUALS"}]}' > "$CRITICAL"
+
+    printf "Total CRITICAL findings count (if any): $(${JQ_CLI} '.[] | length' < "$CRITICAL" )\n"
+    printf "Unique issues list (if any): \n"
+    ${JQ_CLI} '.Findings[].Title' < $CRITICAL | sort | uniq  | tr -d '"' | sed 's/^/- /'
+
+    ${AWS_CLI}  securityhub get-findings --filters '{"SeverityLabel":[{"Value": "HIGH","Comparison":"EQUALS"}],"WorkflowStatus": [{"Value":"NEW","Comparison":"EQUALS"}],"RecordState":[{"Value":"ACTIVE","Comparison":"EQUALS"}]}' > "$HIGH"
+    printf "\nTotal HIGH findings count: $(${JQ_CLI} '.[] | length' < "$HIGH" )\n"
+    echo "Unique issues list, if any:"
+    ${JQ_CLI} '.Findings[].Title' < $HIGH | sort | uniq  | tr -d '"' | sed 's/^/- /'
+
+    aws securityhub get-findings --filters '{"SeverityLabel":[{"Value": "MEDIUM","Comparison":"EQUALS"}],"WorkflowStatus": [{"Value":"NEW","Comparison":"EQUALS"}],"RecordState":[{"Value":"ACTIVE","Comparison":"EQUALS"}]}' > "$MEDIUM"
+    printf "\nTotal MEDIUM findings count (if any): $(${JQ_CLI} '.[] | length' < "$MEDIUM" )\n"
+    echo "Unique issues list, if any:"
+    ${JQ_CLI} '.Findings[].Title' < $MEDIUM | sort | uniq  | tr -d '"' | sed 's/^/- /'
+
+    ${AWS_CLI}  securityhub get-findings --filters '{"SeverityLabel":[{"Value": "LOW","Comparison":"EQUALS"}],"WorkflowStatus": [{"Value":"NEW","Comparison":"EQUALS"}],"RecordState":[{"Value":"ACTIVE","Comparison":"EQUALS"}]}' > "$LOW"
+    printf "\nTotal LOW findings count (if any): $(${JQ_CLI} '.[] | length' < "$LOW" )\n"
+    echo "Unique issues list, if any:"
+    ${JQ_CLI} '.Findings[].Title' < $LOW | sort | uniq  | tr -d '"' | sed 's/^/- /'
+
+    ${AWS_CLI}  securityhub get-findings --filters '{"SeverityLabel":[{"Value": "INFO","Comparison":"EQUALS"}],"WorkflowStatus": [{"Value":"NEW","Comparison":"EQUALS"}],"RecordState":[{"Value":"ACTIVE","Comparison":"EQUALS"}]}' > "$INFO"
+    printf "\nTotal INFO findings count (if any): $(${JQ_CLI} '.[] | length' < "$INFO" )\n"
+    echo "Unique issues list, if any:"
+    ${JQ_CLI} '.Findings[].Title' < $INFO | sort | uniq  | tr -d '"' | sed 's/^/- /'
+
+  }; f
 
